// =============================================================================
// Travel Connect Pro — Database Types
// =============================================================================
// AUTO-GENERATED by: npm run types:gen
// Source: supabase gen types typescript --project-id pjyjblllcllnqsjbvbfc
//
// DO NOT EDIT BY HAND. Run the command above to regenerate after schema changes.
// =============================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// This file is intentionally minimal — run `npm run types:gen` to populate it
// with the full generated type tree from your live Supabase schema.
export interface Database {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
  }
}

// ─── Convenience re-exports ───────────────────────────────────────────────────
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T] extends { Row: infer R } ? R : never

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T] extends { Insert: infer I } ? I : never

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T] extends { Update: infer U } ? U : never
